version: "3.6"

services:
  sut:
    image: damiantroy/jackett:${CACHE_TAG}
    volumes:
      - jackett_config:/config
    command: >
      bash -c "/opt/Jackett/jackett --NoUpdates --DataFolder=/config &
               test.sh -t 30 -u http://localhost:9117/torznab/all/api -e 'error code=\"100\"'"

volumes:
  jackett_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
